// scripts/generate-cities.ts
import { rawTimeZones } from '@vvo/tzdb';
import { writeFileSync } from 'fs';

function toSlug(name: string): string {
  return name
    .normalize('NFD')                          // decompose accented chars (é → e + combining accent)
    .replace(/[\u0300-\u036f]/g, '')           // strip combining diacritical marks
    .replace(/[^\x00-\x7F]/g, '-')             // replace any remaining non-ASCII with hyphen
    .toLowerCase()
    .replace(/[\s,.'()']/g, '-')               // spaces, punctuation → hyphen (including curly quote)
    .replace(/-+/g, '-')                       // collapse multiple hyphens
    .replace(/^-|-$/g, '');                    // trim leading/trailing hyphens
}

interface CityEntry {
  slug: string;
  name: string;
  country: string;
  timezone: string;
}

const seen = new Set<string>();
const cities: CityEntry[] = [];

for (const tz of rawTimeZones) {
  for (const cityName of tz.mainCities) {
    const slug = toSlug(cityName);
    if (seen.has(slug)) continue;
    seen.add(slug);
    cities.push({
      slug,
      name: cityName,
      country: tz.countryName ?? '',
      timezone: tz.name,
    });
  }
}

cities.sort((a, b) => a.slug.localeCompare(b.slug));

const output = `// AUTO-GENERATED by scripts/generate-cities.ts — do not edit manually
// Source: @vvo/tzdb
export interface CityEntry {
  slug: string;
  name: string;
  country: string;
  timezone: string; // IANA zone name
}

export const cities: CityEntry[] = ${JSON.stringify(cities, null, 2)};

export default cities;
`;

writeFileSync('src/data/cities.ts', output, 'utf-8');
console.log(`Generated ${cities.length} cities → src/data/cities.ts`);
