name = "whatisthetime-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "KEYS"
id = "dbabd83cc4be4ebfb3069c183ab32eca"

[[kv_namespaces]]
binding = "RATE"
id = "d71d63194e6e497f86b7531fa6d07b5a"

[[routes]]
pattern = "api.whatisthetime.now/*"
zone_name = "whatisthetime.now"
